### ISSUE TITLE
Is there an easy way to get this up and running on Heroku?

### ISSUE THREAD

**Issue by argoapps** [casperbh96/Flask-Stripe-MySQL-Bootstrapped#7]
Hi, great work on this, thanks very much for your time and effort, it is very helpful and useful.

I am wondering if there is an easy way to get this up and running on Heroku.  I have been struggling for two days trying to work it out.  I think there would be a seperate dyno per Dockerfile, and understand I may have to use a heroku.yml for this but I am stuck and unsure if this is the correct thing to do. 

Any help would be great, thanks once again.

**Comment by casperbh96** [comment]
This type of application is not supported well on Heroku. Heroku is more like deploying instances of specific applications whereas you need container technology for this template. You could probably make it work with separate containers on Heroku, but that would be messy. I suggest you choose another cloud platform that supports Kubernetes - then you just have to convert the docker compose file to Kubernetes configuration files.

**Comment by argoapps** [comment]
Appreciate the help, thank you.
