### ISSUE TITLE
Communication error between ports when deployed on Google Cloud Run 

### ISSUE THREAD

**Issue by argoapps** [casperbh96/Flask-Stripe-MySQL-Bootstrapped#8]
Thank you once again for your time and effort making this.  It has been extremely useful from a learning experience understanding this microservice and learning more about python while using this template to create my app.

I have deployed each container on Google Cloud Run on a public URL.  Database is up and running and creating the databases and all tables. The frontend loads templates load fine but I am having issues communicating between ports.  I try to register and I am getting communication errors. [Errno 111] Connection refused

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /signup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x3ed7ce7b5e50>: Failed to establish a new connection: [Errno 111] Connection refused')

I have all containers running on their respective ports but I am unsure why this works fine locally but not on Cloud Run on Google.  Is there something obvious I am missing or do I need to change something?

<img width="1021" alt="Screenshot 2021-09-22 at 13 35 31" src="https://user-images.githubusercontent.com/80706503/134492209-4675e9b0-1c9a-44ec-bab5-856a1d928299.png">

**Comment by casperbh96** [comment]
If there is a communication issue, you should look at the host and port.

1. Is the host the correct IP address? Perhaps localhost should be changed to the IP address of the service you are trying to reach.
2. Do these services allow traffic through their IP address and the specific port number that you specify?

**Comment by argoapps** [comment]
Thanks for the response, very much appreciate your help.

I don't seem to have an IP address for each container/service on Google Cloud Run.  I do have a unique fixed URLs for each container/service.  I tried changing the localhost to the URL for the specific container/service but it didn't work.

I am now looking at how to assign a static IP address to all services as there doesn't seem to be one by default.

I have allowed "All Traffic" on all services when setting up and I thought that would be enough.

<img width="486" alt="Screenshot 2021-09-23 at 13 45 32" src="https://user-images.githubusercontent.com/80706503/134509185-a687807d-cb4a-4af2-a55a-a39e91d450e6.png">

<img width="489" alt="Screenshot 2021-09-23 at 13 45 51" src="https://user-images.githubusercontent.com/80706503/134509421-678506d6-1b0f-4f88-a2c4-b9faa477a54d.png">

**Comment by argoapps** [comment]
Am I correct in assuming I would need an internal HTTP load_balancer for this?

<img width="883" alt="Screenshot 2021-09-23 at 15 52 42" src="https://user-images.githubusercontent.com/80706503/134530738-90caf3cc-16f1-414a-b5af-a7c2cf2048a6.png">
is

**Comment by casperbh96** [comment]
This is Google's guide on service-to-service communication. I believe this issue is outside the scope of the repository.

Good luck on your journey!

**Comment by argoapps** [comment]
Appreciate your help and guidance, thank you
